---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9@sha256:63f6ab844b31c90712b04908e8b995d8fc9d2dab8d36b8fe729d8e186a07fd84
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core==2.18.2,<2.19
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  galaxy: requirements.yml
  system: bindep.txt
  python: requirements.txt
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - >-
      COPY
      --from=quay.io/ansible/receptor:v1.4.8@sha256:39cfed2650f8576e01d2dcd520f1f4edf76609d88e2978bed55c447ffc16285f
      /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
