---
collections:
  - name: awx.awx
    version: 24.4.0
  - name: azure.azcollection
    version: 2.3.0
  - name: amazon.aws
    version: 8.0.0
  - name: theforeman.foreman
    version: 4.0.0
  - name: google.cloud
    version: 1.3.0
  - name: openstack.cloud
    version: 2.2.0
  - name: community.vmware
    version: 4.3.0
  - name: ovirt.ovirt
    version: 3.2.0
  - name: kubernetes.core
    version: 4.0.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.windows
    version: 2.3.0
  - name: redhatinsights.insights
    version: 1.2.2
  - name: kubevirt.core
    version: 1.3.2
