---

name: CI

on:
  pull_request:
    branches:
      - devel-pinned
      # - feature-renovate

  # push:
  #   branches:
  #     - devel-pinned

jobs:
  podman:
    runs-on: ubuntu-22.04
    name: Podman
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install tox

      - name: Build EE with Podman
        run: |
          tox -e podman

  docker:
    runs-on: ubuntu-22.04
    name: Docker
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install tox

      - name: Build EE with Docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker
